[env]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
    madhephaestus/ESP32Servo
monitor_speed = 115200
board_build.filesystem = littlefs

; Główny projekt
[env:main]
; Kompiluj wszystko w src/, ale zignoruj main_debugging.cpp
build_src_filter = +<*> -<main_debugging.cpp>

; Projekt testowy
[env:debug_test]
; Zignoruj plik main.cpp i całą strukturę OOP (foldery machine, motion, web),
; skompiluj tylko main_debugging.cpp
build_src_filter = +<main_debug.cpp> -<main.cpp> -<machine/> -<motion/> -<web/>